### ISSUE TITLE
Kondor Improvements 

### ISSUE THREAD

**Issue by brklyn8900** [joticajulian/kondor#39]
As a Kondor user I would like to have a good interface so that I can have a pleasurable user experience when using the wallet

- [ ] Improve pop-up and settings page design #40
- [ ] Parse JSON in pop-up #41 
- [ ] Add new icon #42 
- [ ] Make address click and copy #43 
- [ ] Autofocus password field on startup #44 
- [ ] Fix button alignment on some screens #45 
- [ ] Available accounts scrolling issue #46 
- [ ] 	Available accounts improve design #47 
- [ ] 12 word phrase verification #48 
- [ ] verify address checksum during a transfer #51
